name: Deploy to Azure Web App (manual)

on:
  # Keep this workflow as a manual fallback to avoid duplicate deployments.
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: gopiportfolioapp
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  NODE_VERSION: '22.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci

      - name: Build
        run: |
          npm run build

      # Optional: keep artifact for debugging
      - name: Archive project
        run: |
          zip -r release.zip . -x "**/.git**" "**/node_modules/**" "**/.next/cache/**"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: release.zip

      # Ensure the app uses the right start command (package.json -> "start": "next start")
      # If you set App Settings in Azure Portal: SCM_DO_BUILD_DURING_DEPLOYMENT=true to let Oryx build server-side
