# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - gopiportfolioapp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install production dependencies and build
        shell: pwsh
        run: |
          npm ci --omit=dev
          npm run build

      - name: Create deployable package (minimal)
        shell: pwsh
        run: |
          Remove-Item -Recurse -Force release -ErrorAction SilentlyContinue
          New-Item -ItemType Directory -Path release | Out-Null
          # Copy runtime files only
          Copy-Item -Recurse -Force .next release/.next
          Copy-Item -Recurse -Force public release/public
          Copy-Item package.json release/package.json
          if (Test-Path package-lock.json) { Copy-Item package-lock.json release/package-lock.json }
          # Trim cache to reduce size
          if (Test-Path 'release/.next/cache') { Remove-Item -Recurse -Force 'release/.next/cache' }
      
    - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
      name: webapp
      path: release

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: webapp
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4571C39307A1445592B937E1B8C9E9BE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D4314A9CCCB249268727C7E43EDE30D8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_01265870DE014D928D3FFA3EB1A7AE40 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'gopiportfolioapp'
          slot-name: 'Production'
          package: ./webapp
          