# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - gopiportfolioapp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Create dist folder for deployment (standalone)
        shell: pwsh
        run: |
          if (Test-Path dist) { Remove-Item -Recurse -Force dist }
          New-Item -ItemType Directory -Path dist | Out-Null
          # Copy standalone server bundle contents (so server.js is at dist root)
          Get-ChildItem ".next/standalone" -Force | Copy-Item -Destination dist -Recurse -Force
          # Ensure entry file exists at dist root (Next can emit server.js or server.cjs)
          if (Test-Path ".next/standalone/server.js") { Copy-Item ".next/standalone/server.js" "dist/server.js" -Force }
          elseif (Test-Path ".next/standalone/server.cjs") { Copy-Item ".next/standalone/server.cjs" "dist/server.js" -Force }
          # Ensure .next/static is present for assets
          New-Item -ItemType Directory -Path dist/.next -ErrorAction SilentlyContinue | Out-Null
          if (Test-Path ".next/static") { Copy-Item -Recurse -Force ".next/static" "dist/.next/static" }
          # Public assets if any
          if (Test-Path public) { Copy-Item -Recurse -Force public dist/public }
          # IIS web.config to route to server.js
          if (Test-Path web.config) { Copy-Item web.config dist/web.config }
            # Diagnostics and fail-fast if server.js is missing
            Write-Host "Listing .next/standalone contents:"; Get-ChildItem -Recurse -File ".next/standalone" | Select-Object -ExpandProperty FullName
            Write-Host "Listing dist root:"; Get-ChildItem dist | Select-Object Name,Length
            if (!(Test-Path "dist/server.js") -and !(Test-Path "dist/server.cjs")) {
              Write-Host "ERROR: server.js (or server.cjs) not found in dist."
              exit 1
            }
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: ./dist
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0ED379D91F064B2D8C3D3038C3EE38C7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_784E1F77BC074AC09FF00C08900CB421 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_226A0C6D968C445B92611B887EAA937E }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'gopiportfolioapp'
          slot-name: 'Production'
          package: ./dist 
